SOLAR_TEMP   = 28
AVG_HUMIDITY = 64

ROMANIAN_PLANTS_DB = [
    {"name": "Afine",            "emoji": "🫐", "hum_threshold": 65},
    {"name": "Anghinare",        "emoji": "🌿", "hum_threshold": 60},
    {"name": "Ardei",            "emoji": "🫑", "hum_threshold": 60},
    {"name": "Ardei iuti",       "emoji": "🌶", "hum_threshold": 55},
    {"name": "Broccoli",         "emoji": "🥦", "hum_threshold": 65},
    {"name": "Busuioc",          "emoji": "🌿", "hum_threshold": 60},
    {"name": "Capsuni",          "emoji": "🍓", "hum_threshold": 65},
    {"name": "Cartofi",          "emoji": "🥔", "hum_threshold": 60},
    {"name": "Castraveti",       "emoji": "🥒", "hum_threshold": 70},
    {"name": "Ceapa",            "emoji": "🧅", "hum_threshold": 50},
    {"name": "Cimbru",           "emoji": "🌿", "hum_threshold": 40},
    {"name": "Cires",            "emoji": "🍒", "hum_threshold": 55},
    {"name": "Conopida",         "emoji": "🥦", "hum_threshold": 65},
    {"name": "Dovleac",          "emoji": "🎃", "hum_threshold": 60},
    {"name": "Dovlecel",         "emoji": "🥒", "hum_threshold": 65},
    {"name": "Fasole",           "emoji": "🫘", "hum_threshold": 60},
    {"name": "Floarea soarelui", "emoji": "🌻", "hum_threshold": 50},
    {"name": "Lavanda",          "emoji": "💜", "hum_threshold": 35},
    {"name": "Loboda",           "emoji": "🌿", "hum_threshold": 65},
    {"name": "Marar",            "emoji": "🌿", "hum_threshold": 55},
    {"name": "Mazare",           "emoji": "🟢", "hum_threshold": 65},
    {"name": "Menta",            "emoji": "🌿", "hum_threshold": 65},
    {"name": "Mere",             "emoji": "🍎", "hum_threshold": 50},
    {"name": "Morcovi",          "emoji": "🥕", "hum_threshold": 55},
    {"name": "Patrunjel",        "emoji": "🌿", "hum_threshold": 55},
    {"name": "Pere",             "emoji": "🍐", "hum_threshold": 55},
    {"name": "Porumb",           "emoji": "🌽", "hum_threshold": 65},
    {"name": "Prune",            "emoji": "🍑", "hum_threshold": 55},
    {"name": "Ridichi",          "emoji": "🔴", "hum_threshold": 60},
    {"name": "Rosii",            "emoji": "🍅", "hum_threshold": 65},
    {"name": "Rozmarin",         "emoji": "🌿", "hum_threshold": 40},
    {"name": "Salata",           "emoji": "🥬", "hum_threshold": 70},
    {"name": "Sfecla rosie",     "emoji": "🔴", "hum_threshold": 60},
    {"name": "Spanac",           "emoji": "🥬", "hum_threshold": 65},
    {"name": "Struguri",         "emoji": "🍇", "hum_threshold": 55},
    {"name": "Telina",           "emoji": "🌿", "hum_threshold": 70},
    {"name": "Usturoi",          "emoji": "🧄", "hum_threshold": 45},
    {"name": "Varza",            "emoji": "🥬", "hum_threshold": 65},
    {"name": "Vinete",           "emoji": "🍆", "hum_threshold": 60},
    {"name": "Zmeura",           "emoji": "🍓", "hum_threshold": 60},
]